data logi_systemowe;
    do i = 1 to 1000;
        ID = i;
        if mod(i, 2) = 1 then RODZAJ = 'LOGOWANIE';
        else if mod(i, 5) = 0 then RODZAJ = 'WYLOGOWANIE';
        else if mod(i, 7) = 0 then RODZAJ = 'POBRANIE_PLIKU';
        else RODZAJ = 'WYSWIETLENIE_FORMULARZA';
        CZAS_AKTYWNOSCI = '2022-08-01T00:00:01.000000+00:00'dt + (i-1)*60;
        if mod(i, 3) = 1 then LOGIN = 'j.kowalski';
        else if mod(i, 3) = 2 then LOGIN = 'a.nowak';
        else LOGIN = 'm.nowicka';
        output;
    end;
    format CZAS_AKTYWNOSCI datetime20.;
    drop i;
run;